### ISSUE TITLE
If previous workspace no longer exists, the perforce plugin fatally dies during the sync step

### ISSUE THREAD

**Issue by improbable-mattchurch** [improbable-eng/perforce-buildkite-plugin#250]
Note: the workspace `bk-p4-bk-9b156f51bd97dc3de6ea8aaa4b20a14f5eba4d5d-vbbn-1-midwinter` must have been cleaned up or removed.
```
17:21:33 p4python WARNING: p4config last client was bk-p4-bk-9b156f51bd97dc3de6ea8aaa4b20a14f5eba4d5d-vbbn-1-midwinter, flushing workspace to match
--
  | 17:21:33 p4python INFO: p4 client -o bk-p4-bk-9b156f51bd97dc3de6ea8aaa4b20a14f5eba4d5d-vbbn-1-midwinter
  | Traceback (most recent call last):
  | File "c:/users/buildkite-agent/AppData/Local/buildkite-agent/plugins/github-com-improbable-eng-perforce-buildkite-plugin-v4-5-0/hooks/../python/checkout.py", line 38, in <module>
  | main()
  | File "c:/users/buildkite-agent/AppData/Local/buildkite-agent/plugins/github-com-improbable-eng-perforce-buildkite-plugin-v4-5-0/hooks/../python/checkout.py", line 24, in main
  | repo.sync(revision=revision)
  | File "c:\users\buildkite-agent\AppData\Local\buildkite-agent\plugins\github-com-improbable-eng-perforce-buildkite-plugin-v4-5-0\python\perforce.py", line 234, in sync
  | self._setup_client()
  | File "c:\users\buildkite-agent\AppData\Local\buildkite-agent\plugins\github-com-improbable-eng-perforce-buildkite-plugin-v4-5-0\python\perforce.py", line 145, in _setup_client
  | self._flush_to_previous_client(client, prev_clientname)
  | File "c:\users\buildkite-agent\AppData\Local\buildkite-agent\plugins\github-com-improbable-eng-perforce-buildkite-plugin-v4-5-0\python\perforce.py", line 94, in _flush_to_previous_client
  | stream_switch = self.stream and prev_client._stream != self.stream
  | File "C:\b\.perforce-plugin-venv-9ff2ccc560797bedf57c60e7f0f0c651\lib\site-packages\P4.py", line 102, in __getattr__
  | return self[self.__fields[key]]
  | KeyError: 'Stream'
```

Error source: https://buildkite.com/improbable/midwinter-build/builds/9417#8cb06b87-14ac-4142-a46b-fd04991b17bf/206-217

**Comment by improbable-mattchurch** [comment]
In order to work around this issue, I'm going to create a workspace matching that name and set the stream value so I can create a historic build that is required
