### ISSUE TITLE
Provide a better error vs empty shelved changes

### ISSUE THREAD

**Issue by ca-johnson** [improbable-eng/perforce-buildkite-plugin#83]
Currently, this error surfaces when trying to make a copy of the shelved files.

Instead, we should raise a more informative error saying "change X did not contain any shelved files that are mapped into this workspace/stream"

```
18:33:09 p4python INFO: p4 sync -q --parallel=threads=0 //depot/dev/.buildkite/...@11702
--
  | 18:33:10 p4python INFO: p4 revert //...
  | 18:33:10 p4python WARNING: //... - file(s) not opened on this client.
  | 18:33:10 p4python INFO: p4 unshelve -s 11678
  | 18:33:10 p4python WARNING: Change 11678 - no file(s) to unshelve.
  | 18:33:10 p4python INFO: p4 change -o
  | 18:33:10 p4python INFO: p4 change -i
  | 18:33:11 p4python INFO: Change 11705 created.
  | 18:33:11 p4python INFO: p4 changes -c client-name -s pending -m 1
  | 18:33:11 p4python INFO: p4 shelve -c 11705
  | 18:33:11 p4python ERROR: No files to shelve.
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/plugins/github-com-ca-johnson-perforce-buildkite-plugin-override-git-metadata/hooks/../python/checkout.py", line 44, in <module>
  | main()
  | File "/var/lib/buildkite-agent/plugins/github-com-ca-johnson-perforce-buildkite-plugin-override-git-metadata/hooks/../python/checkout.py", line 35, in main
  | changelist = repo.backup(user_changelist)
  | File "/var/lib/buildkite-agent/plugins/github-com-ca-johnson-perforce-buildkite-plugin-override-git-metadata/python/perforce.py", line 165, in backup
  | self.perforce.run_shelve('-c', backup_cl)
  | File "/var/lib/buildkite-agent/.local/lib/python2.7/site-packages/P4.py", line 646, in run_shelve
  | return self.run("shelve", *nargs, **kargs)
  | File "/var/lib/buildkite-agent/.local/lib/python2.7/site-packages/P4.py", line 611, in run
  | raise e
  | P4.P4Exception: [P4#run] Errors during command execution( "p4 shelve -c 11705" )
  |  
  | [Error]: 'No files to shelve.'
```

**Comment by ca-johnson** [comment]
Addressed in #103
